version: '3.8'

services:
  azdo-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azdo-agent
    environment:
      AZP_URL: https://dev.azure.com/foxtechniques
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_POOL: azdoba-pool
      AZP_AGENT_NAME: azdo-agent-${HOSTNAME}
    volumes:
      - ./agentdata:/azdo/_work
      - ./logs:/azdo/logs
      - ./agentdata/_diag:/azdo/_diag
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep Agent.Listener || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
